<html>
<head>
	<meta charset="utf-8">
	<title>Portfolio Alix</title>
	<link href="css/error.css" rel="stylesheet">
</head>
<body>
	<h1>404</h1>

	<div class="frame">
   		<div></div>
    	<div></div>
   		<div></div>
	</div>
	<div class="caps"><img src="http://ademilter.com/caps.png" alt=""></div>
	<canvas id="canvas"></canvas>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="js/calls.js"></script>
</body>
</html>

