<html lang="fr">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Portfolio Alix</title>
	<link rel="icon" type="image/png" href="img/Portrait.png" />
	<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="bootstrap/font-awesome-4.4.0/css/font-awesome.min.css">
	<link href="css/style.css" rel="stylesheet">
</head>
<body>
	<!--////////////////// MENU //////////////////////-->
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header page-scroll">
				<button type="button" data-toggle="collapse" data-target="#menu" class="navbar-toggle collapsed" aria-expanded="false">
					<span class="sr-only">Menu</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="#main" class="navbar-brand">Alix</a>
			</div>
			<div id="menu" class="navbar-collapse collapse" aria-expanded="false">
				<ul class="nav navbar-nav navbar-right">
					<li class="page-scroll"><a href="#a-propos">A propos</a></li>
					<li class="page-scroll"><a href="#competences">Compétences</a></li>
					<li class="page-scroll"><a href="#parcours">Parcours</a></li>
					<li class="page-scroll"><a href="#portfolio">Portfolio</a></li>
					<li class="page-scroll"><a href="#contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<?= $this->view->getContent() ?>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="bootstrap/js/bootstrap.min.js"></script>
	<script src="js/calls.js"></script>

</body>
</html>